/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photonvision_vision_apriltag_AprilTagJNI */

#ifndef _Included_org_photonvision_vision_apriltag_AprilTagJNI
#define _Included_org_photonvision_vision_apriltag_AprilTagJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photonvision_vision_apriltag_AprilTagJNI
 * Method:    AprilTag_Create
 * Signature: (Ljava/lang/String;DDIZZ)J
 */
JNIEXPORT jlong JNICALL Java_org_photonvision_vision_apriltag_AprilTagJNI_AprilTag_1Create
  (JNIEnv *, jclass, jstring, jdouble, jdouble, jint, jboolean, jboolean);

JNIEXPORT void JNICALL Java_org_photonvision_vision_apriltag_AprilTagJNI_AprilTag_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_photonvision_vision_apriltag_AprilTagJNI
 * Method:    AprilTag_Detect
 * Signature: (JJII)[Lorg/photonvision/vision/apriltag/DetectionResult;
 */
JNIEXPORT jobjectArray JNICALL Java_org_photonvision_vision_apriltag_AprilTagJNI_AprilTag_1Detect
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
